//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.GameBackend.CloudSave.Http;



namespace Unity.GameBackend.CloudSave.Models
{
    /// <summary>
    /// GetKeysResponse model
    /// <param name="results">results param</param>
    /// <param name="links">links param</param>
    /// </summary>

    [Preserve]
    [DataContract(Name = "get-keys-response")]
    public class GetKeysResponse
    {
        /// <summary>
        /// Creates an instance of GetKeysResponse.
        /// </summary>
        /// <param name="results">results param</param>
        /// <param name="links">links param</param>
        [Preserve]
        public GetKeysResponse(List<KeyMetadata> results, GetItemsResponseLinks links)
        {
            Results = results;
            Links = links;
        }

        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<KeyMetadata> Results{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public GetItemsResponseLinks Links{ get; }
    
    }
}

