//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.GameBackend.CloudSave.Http;



namespace Unity.GameBackend.CloudSave.Models
{
    /// <summary>
    /// ModifiedMetadata model
    /// <param name="date">Date time in ISO 8601 format. Null if there is no associated value.</param>
    /// </summary>

    [Preserve]
    [DataContract(Name = "modified-metadata")]
    public class ModifiedMetadata
    {
        /// <summary>
        /// Creates an instance of ModifiedMetadata.
        /// </summary>
        /// <param name="date">Date time in ISO 8601 format. Null if there is no associated value.</param>
        [Preserve]
        public ModifiedMetadata(DateTime? date)
        {
            Date = date;
        }

        /// <summary>
        /// Date time in ISO 8601 format. Null if there is no associated value.
        /// </summary>
        [Preserve]
        [DataMember(Name = "date", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? Date{ get; }
    
    }
}

