//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;



namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [Preserve]
    [DataContract(Name = "ConflictErrorResponseData")]
    internal class ConflictErrorResponseData
    {
        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        /// <param name="attempted">attempted param</param>
        /// <param name="existing">existing param</param>
        [Preserve]
        public ConflictErrorResponseData(AttemptedItem attempted = default, Item existing = default)
        {
            Attempted = attempted;
            Existing = existing;
        }

        /// <summary>
        /// Parameter attempted of ConflictErrorResponseData
        /// </summary>
        [Preserve]
        [DataMember(Name = "attempted", EmitDefaultValue = false)]
        public AttemptedItem Attempted{ get; }

        /// <summary>
        /// Parameter existing of ConflictErrorResponseData
        /// </summary>
        [Preserve]
        [DataMember(Name = "existing", EmitDefaultValue = false)]
        public Item Existing{ get; }

        /// <summary>
        /// Formats a ConflictErrorResponseData into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Attempted != null)
            {
                serializedModel += "attempted," + Attempted.ToString() + ",";
            }
            if (Existing != null)
            {
                serializedModel += "existing," + Existing.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a ConflictErrorResponseData as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
