//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;



namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// ConflictErrorResponseAllOf model
    /// </summary>
    [Preserve]
    [DataContract(Name = "ConflictErrorResponse_allOf")]
    internal class ConflictErrorResponseAllOf
    {
        /// <summary>
        /// Creates an instance of ConflictErrorResponseAllOf.
        /// </summary>
        /// <param name="data">data param</param>
        [Preserve]
        public ConflictErrorResponseAllOf(ConflictErrorResponseData data = default)
        {
            Data = data;
        }

        /// <summary>
        /// Parameter data of ConflictErrorResponseAllOf
        /// </summary>
        [Preserve]
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public ConflictErrorResponseData Data{ get; }

        /// <summary>
        /// Formats a ConflictErrorResponseAllOf into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Data != null)
            {
                serializedModel += "data," + Data.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a ConflictErrorResponseAllOf as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
