//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;



namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// FileListLinks model
    /// </summary>
    [Preserve]
    [DataContract(Name = "FileList_links")]
    internal class FileListLinks
    {
        /// <summary>
        /// Creates an instance of FileListLinks.
        /// </summary>
        /// <param name="next">next param</param>
        [Preserve]
        public FileListLinks(string next = default)
        {
            Next = next;
        }

        /// <summary>
        /// Parameter next of FileListLinks
        /// </summary>
        [Preserve]
        [DataMember(Name = "next", EmitDefaultValue = false)]
        public string Next{ get; }

        /// <summary>
        /// Formats a FileListLinks into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Next != null)
            {
                serializedModel += "next," + Next;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a FileListLinks as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Next != null)
            {
                var nextStringValue = Next.ToString();
                dictionary.Add("next", nextStringValue);
            }

            return dictionary;
        }
    }
}
