//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;



namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// FileList model
    /// </summary>
    [Preserve]
    [DataContract(Name = "FileList")]
    internal class FileList
    {
        /// <summary>
        /// Creates an instance of FileList.
        /// </summary>
        /// <param name="results">results param</param>
        /// <param name="links">links param</param>
        [Preserve]
        public FileList(List<FileItem> results = default, FileListLinks links = default)
        {
            Results = results;
            Links = links;
        }

        /// <summary>
        /// Parameter results of FileList
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<FileItem> Results{ get; }

        /// <summary>
        /// Parameter links of FileList
        /// </summary>
        [Preserve]
        [DataMember(Name = "links", EmitDefaultValue = false)]
        public FileListLinks Links{ get; }

        /// <summary>
        /// Formats a FileList into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Results != null)
            {
                serializedModel += "results," + Results.ToString() + ",";
            }
            if (Links != null)
            {
                serializedModel += "links," + Links.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a FileList as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
