//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;



namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// GetItemsResponseLinks model
    /// </summary>
    [Preserve]
    [DataContract(Name = "GetItemsResponse_links")]
    internal class GetItemsResponseLinks
    {
        /// <summary>
        /// Creates an instance of GetItemsResponseLinks.
        /// </summary>
        /// <param name="next">Contains the URL path for requesting the next page of results. This value is null when there are no pages remaining.</param>
        [Preserve]
        public GetItemsResponseLinks(string next)
        {
            Next = next;
        }

        /// <summary>
        /// Contains the URL path for requesting the next page of results. This value is null when there are no pages remaining.
        /// </summary>
        [Preserve]
        [DataMember(Name = "next", IsRequired = true, EmitDefaultValue = true)]
        public string Next{ get; }
    
        /// <summary>
        /// Formats a GetItemsResponseLinks into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Next != null)
            {
                serializedModel += "next," + Next;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a GetItemsResponseLinks as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Next != null)
            {
                var nextStringValue = Next.ToString();
                dictionary.Add("next", nextStringValue);
            }
            
            return dictionary;
        }
    }
}
