//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;



namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// GetKeysResponse model
    /// </summary>
    [Preserve]
    [DataContract(Name = "GetKeysResponse")]
    internal class GetKeysResponse
    {
        /// <summary>
        /// Creates an instance of GetKeysResponse.
        /// </summary>
        /// <param name="results">A paged list of keys for the given player, ordered alphabetically in pages of 100.</param>
        /// <param name="links">links param</param>
        [Preserve]
        public GetKeysResponse(List<KeyMetadata> results, GetItemsResponseLinks links)
        {
            Results = results;
            Links = links;
        }

        /// <summary>
        /// A paged list of keys for the given player, ordered alphabetically in pages of 100.
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<KeyMetadata> Results{ get; }
        
        /// <summary>
        /// Parameter links of GetKeysResponse
        /// </summary>
        [Preserve]
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public GetItemsResponseLinks Links{ get; }
    
        /// <summary>
        /// Formats a GetKeysResponse into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Results != null)
            {
                serializedModel += "results," + Results.ToString() + ",";
            }
            if (Links != null)
            {
                serializedModel += "links," + Links.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a GetKeysResponse as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
