//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;



namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// InlineResponse200 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_response_200")]
    internal class InlineResponse200
    {
        /// <summary>
        /// Creates an instance of InlineResponse200.
        /// </summary>
        /// <param name="isProvisioned">Indicates whether the project has been provisioned by the Cloud Save service</param>
        [Preserve]
        public InlineResponse200(bool isProvisioned)
        {
            IsProvisioned = isProvisioned;
        }

        /// <summary>
        /// Indicates whether the project has been provisioned by the Cloud Save service
        /// </summary>
        [Preserve]
        [DataMember(Name = "isProvisioned", IsRequired = true, EmitDefaultValue = true)]
        public bool IsProvisioned{ get; }
    
        /// <summary>
        /// Formats a InlineResponse200 into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "isProvisioned," + IsProvisioned.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a InlineResponse200 as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var isProvisionedStringValue = IsProvisioned.ToString();
            dictionary.Add("isProvisioned", isProvisionedStringValue);
            
            return dictionary;
        }
    }
}
