//-----------------------------------------------------------------------------
//     This file was primarily generated by the C# SDK Code Generator.
//
//     Edits were made to change the id parameter to type string, as the generation from the public API docs
//     resulted in it being treated as an object with a discriminator, which caused results to fail to
//     deserialize correctly.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudSave.Internal.Http;


namespace Unity.Services.CloudSave.Internal.Models
{
    /// <summary>
    /// QueryIndexResponseResultsInner model
    /// </summary>
    [Preserve]
    [DataContract(Name = "QueryIndexResponse_results_inner")]
    internal class QueryIndexResponseResultsInner
    {
        /// <summary>
        /// Creates an instance of QueryIndexResponseResultsInner.
        /// </summary>
        /// <param name="id">id param</param>
        /// <param name="data">The list of data key-value pairs for the entity</param>
        [Preserve]
        public QueryIndexResponseResultsInner(string id = default, List<Item> data = default)
        {
            Id = id;
            Data = data;
        }

        /// <summary>
        /// Parameter id of QueryIndexResponseResultsInner
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; }

        /// <summary>
        /// The list of data key-value pairs for the entity
        /// </summary>
        [Preserve]
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public List<Item> Data { get; }

        /// <summary>
        /// Formats a QueryIndexResponseResultsInner into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Id != null)
            {
                serializedModel += "id," + Id.ToString() + ",";
            }
            if (Data != null)
            {
                serializedModel += "data," + Data.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a QueryIndexResponseResultsInner as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
