//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using Unity.GameBackend.CloudSave.Apis.Data;


namespace Unity.GameBackend.CloudSave
{
    /// <summary>
    /// CloudSaveService
    /// </summary>
    internal static class CloudSaveService
    {
        /// <summary>
        /// The static instance of CloudSaveService.
        /// </summary>
        public static ICloudSaveService Instance { get; internal set; }
    }

    /// <summary> Interface for CloudSaveService</summary>
    internal interface ICloudSaveService
    {
        
        /// <summary> Accessor for DataApi methods.</summary>
        IDataApiClient DataApi { get; set; }
        

        /// <summary> Configuration properties for the service.</summary>
        Configuration Configuration { get; set; }
    }
}
